# version: '3.8'
# services:
#   selenium:
#     image: selenium/standalone-chrome
#     ports:
#       - "4444:4444"
#     shm_size: 2gb
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
#       interval: 30s
#       timeout: 10s
#       retries: 5

#   app:
#     build:
#       context: .   # Ensure this points to the correct build context
#       dockerfile: Dockerfile
#     depends_on:
#       selenium:
#         condition: service_healthy
#     environment:
#       - SELENIUM_HOST=selenium
#     volumes:
#       - .:/app
#     working_dir: /app
#     command: ["dotnet", "SeleniumCSharp.dll"]
